### ISSUE TITLE
Change clockwise direction of DDHTimerTypeSolid

### ISSUE THREAD

**Issue by instaqwe** [dasdom/DDHTimerControl#3]
Hi, I'm sorry this is probably a really stupid question, but how can I change the direction of the DDHTimerTypeSolid? Currently it's moving anti-clockwise.
I've tried changing the clockwise parameter in some of the functions in drawrect, but I can't get it to work. Needless to say, I'm a beginner. 

Any help would be much appriciated!

**Comment by dasdom** [comment]
I don't get it. Do you want to fill the circle when the number decreases?

**Comment by instaqwe** [comment]
No, sorry. I just want the outer "circle" to go in the other direction. 

Illustration: 
http://imgur.com/a/zrDTm

Currently it's moving anti-clockwise, and I would like it to move clockwise.

**Comment by dasdom** [comment]
Try to change this line `self.minorShapeLayer.strokeEnd = (float)self.minutesOrSeconds/self.maxValue;` to `self.minorShapeLayer.strokeEnd = (1 - (float)self.minutesOrSeconds/self.maxValue);`.

Please let me know if it works.

**Comment by instaqwe** [comment]
It was the majorshape since I use the DDHTimerTypeSolid. 
self.majorShapeLayer.strokeEnd = (1 - (float)self.minutesOrSeconds/self.maxValue);
And I also removed the handlePath as it was still going the other direction, and wasn't really necessary. 
But it works! Thanks a lot :+1:
